// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPVOsbTQcglSUvHQqgRqHbTeKdfel4R0s',
    appId: '1:758311550466:android:9929698f11b0e51d9a711b',
    messagingSenderId: '758311550466',
    projectId: 'dishly-54fa6',
    storageBucket: 'dishly-54fa6.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3bt1edNjFk-2VeYfswUGcOEoL4VlIuG4',
    appId: '1:758311550466:web:7f79e116e6c813aa9a711b',
    messagingSenderId: '758311550466',
    projectId: 'dishly-54fa6',
    authDomain: 'dishly-54fa6.firebaseapp.com',
    storageBucket: 'dishly-54fa6.firebasestorage.app',
    measurementId: 'G-PY64BXKVHN',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3bt1edNjFk-2VeYfswUGcOEoL4VlIuG4',
    appId: '1:758311550466:web:1cf778672ba57f129a711b',
    messagingSenderId: '758311550466',
    projectId: 'dishly-54fa6',
    authDomain: 'dishly-54fa6.firebaseapp.com',
    storageBucket: 'dishly-54fa6.firebasestorage.app',
    measurementId: 'G-QJX4R60WQP',
  );

}